project:
  type: website
  #post-render: site-attachments/docx2pdf.R
  resources:
    - CNAME
    
website:
  title: "Matt Capaldi"
  site-url: "https://capaldi.info"
  description: "Matt Capaldi, education data and information analyst researching transport to college"
  image: "apple-touch-icon.png"
  favicon: "apple-touch-icon.png"
  twitter-card: true
  open-graph: true
  navbar:
    logo: "site-attachments/Logo.png"
    left:
      - href: transport-to-college.qmd
        text: "{{< fa bus >}} Transport to College"
      - href: data-viz-examples.qmd
        text: "{{< fa chart-line >}} Data Viz Examples"
      - href: cv.qmd
        text: "{{< fa file-lines >}} C.V."
    right:
      - text: "{{< fa paper-plane >}} Email Me"
        href: mailto:m.capaldi@ufl.edu
        aria-label: "Email Me"
  page-footer:
    right: 
      - text: "Built with Quarto"
        href: https://quarto.org/docs/websites
      - icon: github
        aria-label: Website Code Available Here
        href: https://github.com/ttalVlatt/ttalVlatt.github.io
    left: "© M J Capaldi 2023"

      
format:
  html:
    theme: lux
    css: styles.css
    toc: false
    email-obfuscation: references

editor: source

