project:
  type: website
  output-dir: docs

website:
  title: "Matt Capaldi"
  description: "Aspiring Education Data Scientist"
  image: "Logo.png"
  favicon: "Logo.png"
  twitter-card: true
  navbar:
    logo: "Logo.png"
    left:
      - href: data-viz-examples.qmd
        text: Data Viz Examples
      - href: cv.qmd
        text: C.V.
    right:
      - icon: github
        href: https://github.com/ttalVlatt
      
format:
  html:
    theme: lux
    css: styles.css
    toc: false
  docx: default

editor: source

