project:
  type: website
  output-dir: docs

website:
  title: "Matt Capaldi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data-viz-examples.qmd
        text: Data Viz Examples
      

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

