project:
  type: website
  output-dir: docs

website:
  title: "Matt Capaldi"
  description: "Aspiring Education Data Scientist"
  image: "Logo.png"
  favicon: "apple-touch-icon.png"
  twitter-card: true
  open-graph: true
  navbar:
    logo: "Logo.png"
    left:
      - href: data-viz-examples.qmd
        text: Data Viz Examples
      - href: cv.qmd
        text: C.V.
    right:
      - icon: envelope
        href: mailto:m.capaldi@ufl.edu
        aria-label: "Contact Me"
      - icon: github
        href: https://github.com/ttalVlatt
        aria-label: "My GitHub Repo"
  page-footer:
    right: 
      - text: "Built with Quarto"
        href: https://quarto.org/docs/websites
      - icon: github
        aria-label: Website Code Available Here
        href: https://github.com/ttalVlatt/ttalVlatt.github.io
    left: "© M J Capaldi 2023"

      
format:
  html:
    theme: lux
    css: styles.css
    toc: false
    email-obfuscation: references

editor: source

