---
title: "Matt Capaldi"
csl: apa.csl
section-bibs-bibliography: references.yaml
filters:
  - section-bibliographies
  - horizontal-rule
citeproc: false
reference-section-title: false
section-bibs-level : 3
bibliography: references.yaml
toc: false
anchor-sections: false
---

*Education data analyst and doctoral student researching at the intersection of transportation and access to college. Data visualization & R enthusiast.*

::: {.content-hidden when-format="html"}

------------------------------------------------------------------------

##### **Website:** <https://ttalVlatt.github.io>

##### **Phone:** +1 (401) 601-2069

##### **Email:** [m.capaldi\@ufl.edu](mailto:m.capaldi@ufl.edu)
:::

# Education

------------------------------------------------------------------------

### Ph.D. Higher Education Administration

*University of Florida, FL (2021 - Present)*

###### **Minor**: Urban and Regional Planning

###### **Research Method Track**: Quantitative Methods

### M.Ed. Research and Evaluation Methodology

*University of Florida, FL (2022 - Present)*

### M.Ed. Student Personnel in Higher Education

*University of Florida, FL (2018 - 2020)*

### B.A. International Relations with Political Science

*University of Birmingham, UK (2014 - 2018)*

###### **Year Abroad**: Providence College, RI

# Technical Skills

------------------------------------------------------------------------

#### R

-   Data wrangling, data visualization, interactive graphics, machine learning, file management, basic regex, mapping & spatial statistics

#### Shiny

-   Developing interactive apps including data visualization dashboards and data collection tools. Primarily use R Shiny, exploring shinyExpress with Python

#### Python

-   Data wrangling, integration of Python & R through Reticulate, exploring natural language processing

#### GitHub

-   Version control of code, collaboration through shared repositories, publishing websites with GitHub Pages

#### Geographic Information Systems

-   Utilize R for most GIS tasks, also familiar with both QGIS and ArcGIS

#### Other Software Including

-   Quarto, Microsoft Office, Qualtrics, SPSS, Stata, Zotero

# Statistical Skills

------------------------------------------------------------------------

#### Regression-Based Analysis

-   Linear regression, logistic regression, geographically weighted regression

#### Spatial Statistics

-   Distances & central features, clustering analysis, spatial autocorrelation, hot-spot analysis, spatial outlier analysis, interpolation

#### Quasi-Experimental Design

-   Propensity score analysis (including machine learning methods)

#### Survival Analysis

-   Cox proportional hazards model

#### Psychometric Models

-   Classical test theory, factor analysis, item response theory, exploring computational psychometrics

# Work Experience

------------------------------------------------------------------------

### Graduate Research Assistant

*University of Florida, FL (August 2021 - Present)*

Work with Dr. Frank Fernandez on research relating to college access, primarily taking responsibility for data-related tasks (gathering, cleaning, analysis, and visualization).

##### **Major Research Projects**

*Campus Climate Vulnerability Project (Summer 2023 - Present)*

-   Built a customized Shiny app for data collection based on sets of images.

*Linking Community Colleges and High Schools in Texas (Fall 2022 - Present)*

-   Created spatial boundaries for TX community college service areas from legislation and Census shapefiles to spatially match community colleges to feeder high schools.

*Merit-Based Financial Aid (Fall 2021 - Present)*

-   Created a new dataset of all state-run merit-based aid programs in the United States including details on dates active, award amount, merit criteria, and funding rules, leading to a new typology being proposed (see Hu et al., 2023).

*Exploring Equitable Higher Education Funding Models in Illinois (Summer 2022)*

-   Collected data on Illinois appropriations for higher education, labor market projections, census data, and institutional behavior, then drafted data visualizations using R (tables, graphs, and maps) for a report targeted at state policy makers.

### Residence Hall Coordinator

*University of Missouri, MO (July 2020 - May 2021)*

### Graduate Community Coordinator

*University of Florida, FL (July 2019 - May 2020)*

### Summer Sessions Graduate Intern

*Georgetown University, DC (May 2019 - July 2019)*

### Graduate Assistant for Industry Relations

*University of Florida, FL (August 2018 - May 2019)*

### Advising Intern

*US-UK Fulbright Commission, UK (January 2018 - June 2018)*

### Student Ambassador

*University of Birmingham, UK (January 2015 - June 2018)*

### Careers Network Student Peer Presenter

*University of Birmingham, UK (September 2017 - June 2018)*

### International Employer Liaison Assistant

*University of Birmingham, UK (June 2017 - August 2017)*

# Teaching Experience

------------------------------------------------------------------------

### EDH 7916 Contemporary Research in Higher Education

*A.K.A. "the R class", an introductory graduate level class on data management, organization, and workflow using R and GitHub.*

#### Teaching Assistant (Spring 2023)

-   Assisted instructor Dr. Ben Skinner by helping students with trouble-shooting and coding skills both in and out of class time.
-   Designed and taught a lesson on working with spatial data and map creation in R. [See the lesson here](https://edquant.github.io/edh7916/lessons/mapping_api.html).

# Publications

------------------------------------------------------------------------

### Peer-Reviewed Articles

::: content-hidden
[@capaldi2023; @hu]
:::

### Reports

::: content-hidden
[@fernandez2023]
:::

### Commentary Articles

::: content-hidden
[@capaldi2021]
:::

### Presentations

::: content-hidden
[@hu2023]
:::
